GET {{host}}/queue/purge-queue
Accept: application/json

###
GET {{host}}/queue/overview

###
POST {{host}}/queue/add-to-queue
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=QH2a6V-W87U"
}

###